#!/bin/bash
echo "extract contigs from repeatexplorer contigs.fa file using seqtk"
echo "usage extract_contigs_RExp.sh CLN contigs.fa , where N is the cluester number"
if [ "$1" = "" ]
then
  echo "missing argument"
  exit
fi

grep $1C $2 | sed 's/\s.*//' | sed 's/>//' > tmp
if grep -q "_" tmp; then
  echo 'satellite!'
else
  echo 'not satellite!'
  sed -i 's/_.*//' tmp
fi
name=$(head -n 1 tmp | grep -Eo 'CL[0-9]+')
seqtk subseq $2 tmp > $name.fa
rm tmp
echo 'ready'
